dependencies {
    // Registrate
    api("com.tterrag.registrate:Registrate:${forge.versions.registrate.get()}")
    jarJar("com.tterrag.registrate:Registrate:${forge.versions.registrate.get()}")

    // JEI
    compileOnly(forge.jei.common.api) { transitive = false }
    compileOnly(forge.jei.forge.api) { transitive = false }
    implementation(forge.jei.forge.impl) { transitive = false }

    // REI
    compileOnlyApi(forge.rei.plugin)
    compileOnlyApi(forge.rei.api)
    compileOnly(forge.rei.forge)

    // Jade
    implementation(forge.jade)

    // TOP
    compileOnlyApi(forge.theoneprobe) { transitive = false }

    // ae2
    compileOnly("org.appliedenergistics:guideme:21.1.1:api")
    runtimeOnly("org.appliedenergistics:guideme:21.1.1")

    implementation("org.appliedenergistics:appliedenergistics2:19.2.17")

    // applied flux
    implementation("curse.maven:glodium-957920:5821676")
    implementation("curse.maven:applied-flux-965012:8204513")

    // applied mekanistics
    implementation("curse.maven:mekanism-268560:6018306")
    implementation("curse.maven:applied-mekanistics-574300:5978711")

    // ars-energistique
    implementation("curse.maven:ars-nouveau-401955:6175894")
    implementation("curse.maven:ars-energistique-905641:6083715")

    runtimeOnly("curse.maven:curios-309927:6076118")
    runtimeOnly("curse.maven:geckolib-388172:6027599")

    // applied exp
    implementation("curse.maven:experiencelib-1156551:5992832")
    implementation("curse.maven:applied-experienced-1157608:6112629")

    // lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    if (System.getenv("RUN_SERVER") == null) {
        runtimeOnly("maven.modrinth:embeddium:1.0.11+mc1.21.1")
    }
}
