name: Check Style in Pull Request
on:
  pull_request_target:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
      contents: read
    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "repo=$HEAD_REPO_NAME" >> $GITHUB_OUTPUT
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: 17
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: download checkstyle
        run: curl -o checkstyle.jar -L https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.15.0/checkstyle-10.15.0-all.jar
      - name: checkstyle
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWDOG_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
        run: java -jar checkstyle.jar -c style.xml -f xml src | reviewdog -f=checkstyle -name="Checkstyle" -reporter=github-pr-review -level=warning